### ISSUE TITLE
Closing Ceremony Article Component

### ISSUE THREAD

**Issue by shunindesuuu** [SAMAHAN-Systems-Development/samahan-palaro-2024#13]
### Closing Ceremony Article Component
- Part of the landing page

### Requirements:
- uses json for the image and data. JSON file must be located under `/src/data`
- uses the Read More button to redirect to said article
- Responsive to mobile

### For the data, refer to the link/s below:
Lookback Data:
https://docs.google.com/document/d/1yxVk32iT7LWs04OdbwgJo6X5vLN_P64LdqZIt9DkH8I/edit?tab=t.0

Opening Images:
https://drive.google.com/drive/folders/1SyUf-37wB9EmxrIDzStjkjvtBeNapLTB

Games Images:
https://drive.google.com/drive/folders/1E8ls9NYlirpWG2skwCDZzJfaY1qdPorC

### **REMINDERS**

- Check `tailwind.config.ts` and look for the configs.

- For the spacing, margin, and etc, you don't have to make it a 1:1 copy from Figma to Code, adjust it if you feel like it is better or if it is right to you. 

![image](https://github.com/user-attachments/assets/1656d01a-d5b9-4162-9415-147ecd0cf916)

**Comment by mary3l** [comment]
@shunindesuuu Closing image from drive is missing or not available
